vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix:         '%images_directory%'
            upload_destination: '%kernel.project_dir%/../web%images_directory%'
